#!/data/data/com.termux/files/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Termux alarm clock."""

from argparse import ArgumentParser
from time import sleep, ctime
from subprocess import run
from random import choices
from schedule import run_pending, every

def vibrate(duration: str) -> None:
    run(("termux-vibrate", "-f", "-d", duration))

def vibrate_pattern(pattern: tuple) -> None:
    for duration in pattern:
        cmd_duration = str(duration)
        vibrate(cmd_duration)
        sleep(duration/1000 + 0.2)

def print_time(text: str) -> None:
    print(text, ctime())

def alarm() -> None:
    pattern = (
        (100,)*32
        + tuple(choices(range(200, 1001), k=64))
    )
    print_time("It is time")
    vibrate_pattern(pattern)

def main() -> None:
    parser = ArgumentParser(description="termux alarm clock")
    parser.add_argument("-t", "--alarm_time", help="set the time")
    parser.add_argument("-e", "--hourly", action="store_true",
                        help="play the alarm hourly")
    args = parser.parse_args()

    on = every()
    alarm_time = args.alarm_time
    if args.hourly:
        on.hour.at("06:00").do(alarm)
    elif alarm_time:
        on.day.at(alarm_time).do(alarm)
    else:
        parser.error("the alarm time is not set")
    run("termux-wake-lock")
    vibrate("600")
    print_time("The alarm is set")
    while True:
        try:
            run_pending()
            sleep(30)
        except KeyboardInterrupt:
            print_time("Keyboard interrupt")
            sleep(0.5)

if __name__ == "__main__":
    main()
