#!/data/data/com.termux/files/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Termux alarm clock."""

from argparse import ArgumentParser
from time import sleep, ctime, time
from random import choices, choice
from string import punctuation
from subprocess import run
from pathlib import Path
from json import loads
from math import ceil


class MusicPlayer:
    FILE = Path.home() / "alarm"
    PLAYER_CMD = "termux-media-player"
    VOLUME_CMD = "termux-volume"
    STREAM = "music"

    def play(self) -> None:
        volume = ceil(self.get_volume(find_max=True)/2)
        self.set_volume(volume)
        run([self.PLAYER_CMD, "play", self.FILE], check=True)

    def stop(self) -> None:
        print("Stopped")
        run([self.PLAYER_CMD, "stop"], check=True)

    def set_volume(self, level: int) -> None:
        run([self.VOLUME_CMD, self.STREAM, str(level)], check=True)

    def get_volume(self, find_max: bool) -> int:
        prefix = "max_" if find_max else ""
        volume_data = run(
            [self.VOLUME_CMD], capture_output=True, text=True, check=True
        )
        streams = loads(volume_data.stdout)
        for stream in streams:
            if stream["stream"] == self.STREAM:
                return stream[prefix + "volume"]
        return 0


music = MusicPlayer()


def vibrate(duration: int) -> None:
    run(["termux-vibrate", "-f", "-d", str(duration)], check=True)


def vibrate_random(repeats: int) -> None:
    pattern = choices(range(100, 901, 200), k=repeats)
    for duration in pattern:
        vibrate(duration)
        sleep(duration/1000 + 0.2)


def notify(minutes: int, seconds: int) -> None:
    run(["clear"], check=True)
    run(["termux-toast", str(minutes)], check=True)
    repeats = 12 if minutes > 99 else 16
    for _ in range(repeats):
        print(f"{choice(punctuation)}{minutes}"*repeats)
        print(f"{minutes}{choice(punctuation)}"*repeats)
    print("\nThe alarm is set on", ctime())
    print("Wake up on", ctime(time() + seconds), "\n")


def alarm(silent: bool) -> None:
    print("Wake up")
    vibrate_random(64)
    if not silent:
        music.play()
    vibrate_random(64)


def main() -> None:
    parser = ArgumentParser(
        description="Termux alarm clock, requires termux-api"
    )
    parser.add_argument(
        "-s", "--silent", action="store_true", help="Do not play music"
    )
    args = parser.parse_args()
    if not music.FILE.exists():
        raise FileNotFoundError(f"Place your music file at {music.FILE}")

    minutes = int(input("How many minutes until the alarm "))
    seconds = minutes*60
    if minutes < 0:
        return
    old_volume = music.get_volume(find_max=False)
    try:
        notify(minutes, seconds)
        run(["termux-wake-lock"], check=True)
        sleep(seconds)
        alarm(args.silent)
    finally:
        music.stop()
        music.set_volume(old_volume)
        run(["termux-wake-unlock"], check=True)


if __name__ == "__main__":
    main()
